# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
